name: build
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle Build
        run: ./gradlew build --no-daemon --stacktrace --no-build-cache
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}

      - name: Zip Stately Build Results
        if: always()
        run: |
          zip stately-collections-build.zip deprecated/stately-collections/build/reports/tests/* -r
          zip stately-iso-collections.zip deprecated/stately-iso-collections/build/reports/tests/* -r
          zip stately-isolate.zip deprecated/stately-isolate/build/reports/tests/* -r

      - name: Upload Stately Collections Build Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: stately-collections-build
          path: stately-collections-build.zip

      - name: Upload Stately Iso Collections Build Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: stately-iso-collections
          path: stately-iso-collections.zip

      - name: Upload Stately Isolate Build Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: stately-isolate
          path: stately-isolate.zip
env:
  GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
